"use client";

import Image from "next/image";
import { motion } from "framer-motion";

/* Terms and Conditions — Figma 853:77882 ("TNc").
 *
 * Opens from "Terms of Service" in settings.
 *
 * The node's artboard is 392 wide, but what the design actually fixes is a
 * 343–344 column centred in it (content at left 24 of 392; header row 343
 * centred — those two only agree at 392). Our sheet is 440, so the column
 * is re-centred at 48.5 rather than the artboard being scaled; scaling
 * would drag the type sizes with it.
 *
 * Header, sheet-relative:
 *   chevron  24×24 at y46, turned 180° so it points back
 *   wordmark 53.88×22.44 just above the title
 *   title    18px SemiBold at y118
 *   rule     343 wide at y159
 *   content  343 wide from y184, sections gap 32, blocks gap 24
 */

const IN_EASE = [0.22, 1, 0.36, 1] as const;

const COL_X = 48.5;
const COL_W = 343;
const HEADER_H = 160;

/* Copy is Figma's verbatim — including 853:77898, where section 2's
 * sub-heading reads "1.2. Definitions", repeating section 1's. That looks
 * like a copy-paste slip in the design file rather than intent, but it is
 * what the node says, so it is reproduced rather than silently corrected. */
const SECTIONS: {
  heading: string;
  blocks: { title?: string; paras: string[]; spaced?: boolean }[];
}[] = [
  {
    heading: "1. Interpretation",
    blocks: [
      {
        title: "1.1. Interpretation and Definitions",
        paras: [
          "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
        ],
      },
      {
        title: "1.2. Definitions",
        paras: [
          "For the purposes of these Terms and Conditions:",
          "“Application” means the software program provided by the Company downloaded by You on any electronic device, named Atlys.",
          "“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
        ],
      },
    ],
  },
  {
    heading: "2. Acknowledgment",
    blocks: [
      {
        title: "1.2. Definitions",
        spaced: true,
        paras: [
          "2.1. These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.",
          "2.2. Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.",
          "2.3. We respect your right to information and aim at providing a transparent set of “Terms”. Please read the terms of this Policy provided below to learn about the “Terms” you will be signing up for. IF YOU DO NOT AGREE TO ANY OF THE TERMS AND CONDITIONS MENTIONED HEREIN KINDLY DO NOT GIVE YOUR CONSENT AND PROCEED FURTHER TO ACCESS THE Application. By giving your consent to proceed forward in order to access the Application, you will be responsible to adhere to the “Terms” mentioned herein.",
          "2.4. The policies or “Terms” as may be prescribed by the “Company” together constitute a legally binding agreement between you and the Company. You are requested to read these Terms carefully before accessing or using the Application.",
          "2.5. This document is an electronic record in terms of the Information Technology Act, 2000 (“IT Act”) and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the IT Act. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
          "2.6. You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.",
          "2.7. Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.",
          "2.8 You acknowledge the grant or refusal of a visa is at the sole discretion of the Embassy and Atlys is neither involved in the process nor is liable or responsible in any manner whatsoever for any delay in processing or grant or rejection of the visa application of any applicant by the Embassy, which reserves the right to ask for further documentation and to refuse the visa application.",
          "2.9 You acknowledge that the Estimated Time of Arrival (“ETA”) or the visa appointment slot as displayed on the website of the Company is indicative and is on the best effort basis of the Company and not binding on the Company.",
        ],
      },
    ],
  },
  {
    heading: "3. Placing Orders for Goods",
    blocks: [
      {
        paras: [
          "By placing an Order for Goods through the Service, You warrant that You are legally capable of entering into binding contracts.",
        ],
      },
    ],
  },
];

export default function TermsPage({ onBack }: { onBack?: () => void }) {
  return (
    <div className="absolute inset-0 overflow-hidden bg-white" style={{ borderRadius: 44 }}>
      <div className="absolute inset-0 overflow-y-auto overflow-x-hidden [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
        <div
          className="absolute flex flex-col gap-[32px]"
          style={{ left: COL_X, top: 184, width: COL_W }}
        >
          {SECTIONS.map((sec, si) => (
            <motion.div
              key={sec.heading}
              className="flex flex-col gap-[24px]"
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.06 + si * 0.05, duration: 0.5, ease: IN_EASE }}
            >
              <p
                className="font-semibold"
                style={{
                  fontSize: 16,
                  lineHeight: "20px",
                  letterSpacing: "-0.64px",
                  color: "#000000",
                }}
              >
                {sec.heading}
              </p>

              {sec.blocks.map((b, bi) => (
                <div key={bi} className="flex flex-col gap-[8px]">
                  {b.title && (
                    <p
                      className="font-semibold"
                      style={{
                        fontSize: 14,
                        lineHeight: "19px",
                        letterSpacing: "-0.14px",
                        color: "#000000",
                      }}
                    >
                      {b.title}
                    </p>
                  )}
                  <div
                    className="font-medium"
                    style={{
                      fontSize: 14,
                      lineHeight: "19px",
                      letterSpacing: "-0.28px",
                      color: "#666666",
                    }}
                  >
                    {b.paras.map((tx, pi) => (
                      <p
                        key={pi}
                        // 853:77899 puts a blank line between every clause;
                        // one line-height of margin is that blank line.
                        style={{ marginTop: pi === 0 ? 0 : b.spaced ? 19 : 0 }}
                      >
                        {tx}
                      </p>
                    ))}
                  </div>
                </div>
              ))}
            </motion.div>
          ))}
        </div>

        <div style={{ height: 3120 }} />
      </div>

      {/* Header block (853:77903). Opaque, so the text scrolls under it. */}
      <div
        className="pointer-events-none absolute left-0 top-0 w-full"
        style={{ height: HEADER_H, background: "#ffffff", zIndex: 5 }}
      />

      <button
        type="button"
        aria-label="Back"
        onClick={onBack}
        className="absolute flex items-center justify-center"
        style={{ zIndex: 6, left: COL_X, top: 46, width: 24, height: 24 }}
      >
        <Image
          src="/assets/profile/tc-chevron.svg"
          alt=""
          width={24}
          height={24}
          // The design reuses chevron_right turned 180° rather than
          // shipping a separate left glyph.
          style={{ width: 24, height: 24, display: "block", transform: "rotate(180deg)" }}
        />
      </button>

      <Image
        src="/assets/profile/tc-atlys.svg"
        alt="atlys"
        width={54}
        height={22}
        className="pointer-events-none absolute"
        style={{ zIndex: 6, left: COL_X, top: 92, width: 53.8805, height: 22.4371 }}
      />

      <p
        className="pointer-events-none absolute whitespace-nowrap font-semibold"
        style={{
          zIndex: 6,
          left: COL_X,
          top: 118,
          fontSize: 18,
          lineHeight: "22px",
          letterSpacing: "-0.72px",
          color: "#000000",
        }}
      >
        Terms and Conditions
      </p>

      <div
        className="pointer-events-none absolute"
        style={{
          zIndex: 6,
          left: COL_X,
          top: 159,
          width: COL_W,
          height: 1,
          background: "#d6d9dc",
        }}
      />
    </div>
  );
}
